# Exclude some directories
exclude = [
    ".git",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "web",
]

# Set the Python version to Python 3.10.
target-version = "py310"

# Set maximum line length
line-length = 120

[lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), and add isort (`I`) and formatting (`W`) codes
select = ["E", "F", "I", "W"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I", "W"]
unfixable = []

[lint.per-file-ignores]
# Ignore some errors in specific files
"tests/*" = ["E501"]

[format]
# Enable auto-formatting
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
